2022-12-13 11:39:32,018 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:39:32,019 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:39:32,019 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:39:32] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:39:32,028 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:39:32] "GET / HTTP/1.1" 200 -
2022-12-13 11:41:28,769 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:41:28,769 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:41:28,770 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:41:28] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:41:28,779 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:41:28] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:10,770 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:44:10,770 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:44:14,272 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:14] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:20,003 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:20] "GET /match/all HTTP/1.1" 200 -
2022-12-13 11:44:24,809 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:44:24,809 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:44:24,810 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:24] "[32mGET /match/create-new/178/331/4 HTTP/1.1[0m" 302 -
2022-12-13 11:44:24,817 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:24,817 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:24,818 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:24] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:44:24,827 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:24] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:30,236 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:30,237 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:30,238 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:30] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:44:30,247 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:30] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:38,105 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:38,105 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:38,106 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:38] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:44:38,116 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:38] "GET / HTTP/1.1" 200 -
2022-12-13 11:45:56,504 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:45:56] "GET / HTTP/1.1" 200 -
2022-12-13 11:46:03,278 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:46:03,278 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:46:36,092 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:46:36] "GET / HTTP/1.1" 200 -
2022-12-13 11:46:45,788 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:46:45,789 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:46:45,790 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:46:45] "[32mGET /match/create-new/178/331/4 HTTP/1.1[0m" 302 -
2022-12-13 11:46:45,808 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:46:45] "GET /match/all HTTP/1.1" 200 -
2022-12-13 11:48:39,862 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:48:39,863 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:49:10,853 :: ERROR :: Error Message
Stack (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 363, in handle
    super().handle()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 31, in create_new_match
    logger.logging.error('Error Message', stack_info=True)
2022-12-13 11:49:10,854 :: ERROR :: Exception on /match/create-new/0/2/3 [GET]
Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 32, in create_new_match
    raise ValueError(f'match can not be created: '
ValueError: match can not be created: round: 3, home_team: 0, away_team: 2
2022-12-13 11:49:10,855 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:49:10] "[35m[1mGET /match/create-new/0/2/3 HTTP/1.1[0m" 500 -
2022-12-13 11:50:53,151 :: ERROR :: Error Message
Stack (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 363, in handle
    super().handle()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 31, in create_new_match
    return redirect(url_for('match.all_matches'))
2022-12-13 11:50:53,151 :: ERROR :: Exception on /match/create-new/0/2/3 [GET]
Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 32, in create_new_match
ValueError: match can not be created: round: 3, home_team: 0, away_team: 2
2022-12-13 11:50:53,151 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:50:53] "[35m[1mGET /match/create-new/0/2/3 HTTP/1.1[0m" 500 -
2022-12-13 11:50:56,808 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:50:56,810 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:50:59,090 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:50:59] "[32mGET /match/create-new/0/2/3 HTTP/1.1[0m" 302 -
2022-12-13 11:50:59,099 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:50:59] "GET /match/all HTTP/1.1" 200 -
2022-12-13 11:51:05,516 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(3331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 3331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:51:05,516 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(3331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 3331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:51:05,518 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:51:05] "[32mGET /match/create-new/178/3331/4 HTTP/1.1[0m" 302 -
2022-12-13 11:51:05,533 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:51:05] "GET /match/all HTTP/1.1" 200 -
2022-12-13 14:04:09,822 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:04:09,822 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:04:45,605 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:04:45] "GET / HTTP/1.1" 200 -
2022-12-13 14:04:55,648 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:04:55] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-13 14:04:55,661 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:04:55] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:05:16,967 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:16] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-13 14:05:16,972 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:16] "GET / HTTP/1.1" 200 -
2022-12-13 14:05:19,131 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:19] "[32mGET /profile_auth_test HTTP/1.1[0m" 302 -
2022-12-13 14:05:19,137 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:19] "GET /auth/login?next=%2Fprofile_auth_test HTTP/1.1" 200 -
2022-12-13 14:05:24,784 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:05:24,784 :: ERROR :: Wrong credentials input
2022-12-13 14:05:24,785 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:24] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:05:24,791 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:24] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:05:30,934 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:05:30,934 :: ERROR :: Wrong credentials input
2022-12-13 14:05:30,935 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:30] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:05:30,941 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:30] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:05:45,233 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:05:45,234 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:45] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:05:45,244 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:45] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:05:56,011 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:56] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:06:33,275 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:06:33] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-13 14:06:33,285 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:06:33] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:16:45,680 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:16:45,680 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:16:55,427 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:16:55,428 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:16:55] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:16:55,445 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:16:55] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:17:03,281 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:17:03] "[33mGET /moderator-test HTTP/1.1[0m" 404 -
2022-12-13 14:17:10,752 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:17:10] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:18:19,430 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:18:19,430 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:18:22,144 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:22] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:18:30,986 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:30] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:18:39,460 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:39] "GET /lineup/full HTTP/1.1" 200 -
2022-12-13 14:18:46,233 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:46] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-13 14:18:46,250 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:46] "GET / HTTP/1.1" 200 -
2022-12-13 14:18:48,079 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:48] "[32mGET /profile_auth_test HTTP/1.1[0m" 302 -
2022-12-13 14:18:48,089 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:48] "GET /auth/login?next=%2Fprofile_auth_test HTTP/1.1" 200 -
2022-12-13 14:18:49,313 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:49] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:18:56,150 :: INFO :: [(bla), (bla@mail.com), (user)]
2022-12-13 14:18:56,151 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:56] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:18:56,160 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:56] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:19:02,961 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:02] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-13 14:19:02,969 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:02] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:19:06,384 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:06] "[32mGET /auth/admin-test HTTP/1.1[0m" 302 -
2022-12-13 14:19:06,392 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:06] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:22:44,321 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:22:44,321 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:23:08,231 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:08] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:23:17,825 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:23:17,826 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:17] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:23:17,836 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:17] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:23:41,247 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:41] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:23:44,519 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:44] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:31:00,440 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:31:00,440 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:31:05,968 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:31:05] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:31:12,517 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:31:12] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:45:48,690 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:45:48] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 15:30:49,724 :: INFO :: 127.0.0.1 - - [13/Dec/2022 15:30:49] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 19:43:42,247 :: ERROR :: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT "user".id AS user_id, "user".name AS user_name, "user".email AS user_email, "user".password AS user_password, "user".role AS user_role 
FROM "user" 
WHERE "user".id = %(id_1)s 
 LIMIT %(param_1)s]
[parameters: {'id_1': '1', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-13 19:43:42,253 :: ERROR :: Exception on /auth/moderator-test [GET]
Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/core/roles.py", line 12, in authorize
    if current_user.role == 2:
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()  # type: ignore[misc]
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "/Users/symphony/Documents/fantasy-application/src/build/create_app.py", line 26, in load_user
    return get_user_by_id(user_id)
  File "/Users/symphony/Documents/fantasy-application/src/crud/auth_operations.py", line 17, in get_user_by_id
    raise err
  File "/Users/symphony/Documents/fantasy-application/src/crud/auth_operations.py", line 13, in get_user_by_id
    user = session.query(User).filter(User.id == user_id).first()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT "user".id AS user_id, "user".name AS user_name, "user".email AS user_email, "user".password AS user_password, "user".role AS user_role 
FROM "user" 
WHERE "user".id = %(id_1)s 
 LIMIT %(param_1)s]
[parameters: {'id_1': '1', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-13 19:43:42,283 :: INFO :: 127.0.0.1 - - [13/Dec/2022 19:43:42] "[35m[1mGET /auth/moderator-test HTTP/1.1[0m" 500 -
2022-12-13 19:45:02,138 :: ERROR :: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
2022-12-13 19:45:02,139 :: ERROR :: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/index.py", line 13, in main
    return render_template('index.html')
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask_login/utils.py", line 407, in _user_context_processor
    return dict(current_user=_get_user())
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "/Users/symphony/Documents/fantasy-application/src/build/create_app.py", line 26, in load_user
    return get_user_by_id(user_id)
  File "/Users/symphony/Documents/fantasy-application/src/crud/auth_operations.py", line 17, in get_user_by_id
    raise err
  File "/Users/symphony/Documents/fantasy-application/src/crud/auth_operations.py", line 13, in get_user_by_id
    user = session.query(User).filter(User.id == user_id).first()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1798, in _execute_context
    conn = self._revalidate_connection()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 645, in _revalidate_connection
    self._invalid_transaction()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 617, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
2022-12-13 19:45:02,142 :: INFO :: 127.0.0.1 - - [13/Dec/2022 19:45:02] "[35m[1mGET / HTTP/1.1[0m" 500 -
2022-12-13 19:45:17,761 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.58.166:5000
2022-12-13 19:45:17,761 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 19:45:27,353 :: INFO :: 127.0.0.1 - - [13/Dec/2022 19:45:27] "GET / HTTP/1.1" 200 -
2022-12-13 19:45:29,302 :: INFO :: 127.0.0.1 - - [13/Dec/2022 19:45:29] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 19:45:35,445 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 19:45:35,447 :: INFO :: 127.0.0.1 - - [13/Dec/2022 19:45:35] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 19:45:35,459 :: INFO :: 127.0.0.1 - - [13/Dec/2022 19:45:35] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 11:36:56,462 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-14 11:36:56,462 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-14 11:37:03,109 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:03] "GET / HTTP/1.1" 200 -
2022-12-14 11:37:03,352 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-14 11:37:07,076 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:07] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-14 11:37:07,086 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:07] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 11:37:14,046 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-14 11:37:14,047 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:14] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-14 11:37:14,057 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:14] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 11:37:20,420 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:20] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-14 11:37:20,428 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:20] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 11:37:57,084 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:37:57] "GET / HTTP/1.1" 200 -
2022-12-14 11:38:06,162 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:06] "GET / HTTP/1.1" 200 -
2022-12-14 11:38:11,553 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:11] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-14 11:38:11,561 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:11] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 11:38:35,851 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-14 11:38:35,851 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-14 11:38:39,710 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:39] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-14 11:38:47,373 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:47] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-14 11:38:51,787 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:51] "[33mGET /auth/ HTTP/1.1[0m" 404 -
2022-12-14 11:38:59,050 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:59] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-14 11:38:59,061 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:38:59] "GET / HTTP/1.1" 200 -
2022-12-14 11:39:00,830 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:39:00] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 11:39:06,071 :: INFO :: [(bla), (bla@mail.com), (user)]
2022-12-14 11:39:06,072 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:39:06] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-14 11:39:06,081 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:39:06] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 11:39:49,976 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:39:49] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-14 11:39:49,993 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:39:49] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 11:39:53,075 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:39:53] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 11:40:39,474 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:39] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-14 11:40:39,479 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:39] "GET / HTTP/1.1" 200 -
2022-12-14 11:40:41,405 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:41] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-14 11:40:41,411 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:41] "GET /auth/login?next=%2Fauth%2Flogout HTTP/1.1" 200 -
2022-12-14 11:40:50,898 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:50] "GET /auth/signup HTTP/1.1" 200 -
2022-12-14 11:40:57,994 :: INFO :: None
2022-12-14 11:40:58,004 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:58] "[32mPOST /auth/signup HTTP/1.1[0m" 302 -
2022-12-14 11:40:58,008 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:40:58] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 11:41:03,265 :: INFO :: [(gla), (gla@mail.com), (user)]
2022-12-14 11:41:03,266 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:41:03] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-14 11:41:03,273 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:41:03] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 11:58:28,665 :: INFO :: 127.0.0.1 - - [14/Dec/2022 11:58:28] "[33mGET /admin HTTP/1.1[0m" 404 -
2022-12-14 12:00:13,157 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:00:13] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-14 12:00:13,165 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:00:13] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 12:00:19,773 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-14 12:00:19,774 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:00:19] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-14 12:00:19,783 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:00:19] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 12:01:06,519 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:01:06] "[33mGET /admin HTTP/1.1[0m" 404 -
2022-12-14 12:02:24,119 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-14 12:02:24,119 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-14 12:02:28,272 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:02:28] "GET /admin HTTP/1.1" 200 -
2022-12-14 12:09:37,282 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:09:37] "[32mGET /admin/update-user-status/4/moderator HTTP/1.1[0m" 302 -
2022-12-14 12:09:37,290 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:09:37] "GET /admin HTTP/1.1" 200 -
2022-12-14 12:09:57,620 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:09:57] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-14 12:09:57,633 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:09:57] "GET / HTTP/1.1" 200 -
2022-12-14 12:09:59,997 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:09:59] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 12:10:04,039 :: INFO :: [(gla), (gla@mail.com), (content manager)]
2022-12-14 12:10:04,040 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:04] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-14 12:10:04,049 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:04] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-14 12:10:10,274 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:10] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-14 12:10:16,207 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:16] "[32mGET /auth/admin-test HTTP/1.1[0m" 302 -
2022-12-14 12:10:16,216 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:16] "GET /auth/login HTTP/1.1" 200 -
2022-12-14 12:10:23,131 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-14 12:10:23,132 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:23] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-14 12:10:23,141 :: INFO :: 127.0.0.1 - - [14/Dec/2022 12:10:23] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-15 14:17:19,958 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-15 14:17:19,958 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-15 14:17:40,261 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:17:40] "GET / HTTP/1.1" 200 -
2022-12-15 14:17:40,442 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:17:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-15 14:17:41,994 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:17:41] "GET /auth/login HTTP/1.1" 200 -
2022-12-15 14:17:46,417 :: INFO :: [(bla), (bla@mail.com), (user)]
2022-12-15 14:17:46,419 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:17:46] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-15 14:17:46,427 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:17:46] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-15 14:17:51,910 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:17:51] "[33mGET /league HTTP/1.1[0m" 404 -
2022-12-15 14:18:33,450 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-15 14:18:33,451 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-15 14:18:36,414 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:18:36] "[32mGET /league HTTP/1.1[0m" 308 -
2022-12-15 14:18:36,453 :: INFO :: 127.0.0.1 - - [15/Dec/2022 14:18:36] "GET /league/ HTTP/1.1" 200 -
