2022-12-13 11:39:32,018 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:39:32,019 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:39:32,019 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:39:32] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:39:32,028 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:39:32] "GET / HTTP/1.1" 200 -
2022-12-13 11:41:28,769 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:41:28,769 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:41:28,770 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:41:28] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:41:28,779 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:41:28] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:10,770 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:44:10,770 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:44:14,272 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:14] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:20,003 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:20] "GET /match/all HTTP/1.1" 200 -
2022-12-13 11:44:24,809 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:44:24,809 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:44:24,810 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:24] "[32mGET /match/create-new/178/331/4 HTTP/1.1[0m" 302 -
2022-12-13 11:44:24,817 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:24,817 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:24,818 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:24] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:44:24,827 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:24] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:30,236 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:30,237 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:30,238 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:30] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:44:30,247 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:30] "GET / HTTP/1.1" 200 -
2022-12-13 11:44:38,105 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:38,105 :: ERROR :: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
2022-12-13 11:44:38,106 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:38] "[32mGET /match/all HTTP/1.1[0m" 302 -
2022-12-13 11:44:38,116 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:44:38] "GET / HTTP/1.1" 200 -
2022-12-13 11:45:56,504 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:45:56] "GET / HTTP/1.1" 200 -
2022-12-13 11:46:03,278 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:46:03,278 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:46:36,092 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:46:36] "GET / HTTP/1.1" 200 -
2022-12-13 11:46:45,788 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:46:45,789 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:46:45,790 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:46:45] "[32mGET /match/create-new/178/331/4 HTTP/1.1[0m" 302 -
2022-12-13 11:46:45,808 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:46:45] "GET /match/all HTTP/1.1" 200 -
2022-12-13 11:48:39,862 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:48:39,863 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:49:10,853 :: ERROR :: Error Message
Stack (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 363, in handle
    super().handle()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 31, in create_new_match
    logger.logging.error('Error Message', stack_info=True)
2022-12-13 11:49:10,854 :: ERROR :: Exception on /match/create-new/0/2/3 [GET]
Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 32, in create_new_match
    raise ValueError(f'match can not be created: '
ValueError: match can not be created: round: 3, home_team: 0, away_team: 2
2022-12-13 11:49:10,855 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:49:10] "[35m[1mGET /match/create-new/0/2/3 HTTP/1.1[0m" 500 -
2022-12-13 11:50:53,151 :: ERROR :: Error Message
Stack (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 363, in handle
    super().handle()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 31, in create_new_match
    return redirect(url_for('match.all_matches'))
2022-12-13 11:50:53,151 :: ERROR :: Exception on /match/create-new/0/2/3 [GET]
Traceback (most recent call last):
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/symphony/.local/share/virtualenvs/fantasy-application-F7-8LHlt/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/symphony/Documents/fantasy-application/src/routes/match.py", line 32, in create_new_match
ValueError: match can not be created: round: 3, home_team: 0, away_team: 2
2022-12-13 11:50:53,151 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:50:53] "[35m[1mGET /match/create-new/0/2/3 HTTP/1.1[0m" 500 -
2022-12-13 11:50:56,808 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 11:50:56,810 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 11:50:59,090 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:50:59] "[32mGET /match/create-new/0/2/3 HTTP/1.1[0m" 302 -
2022-12-13 11:50:59,099 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:50:59] "GET /match/all HTTP/1.1" 200 -
2022-12-13 11:51:05,516 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(3331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 3331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:51:05,516 :: ERROR :: (psycopg2.errors.ForeignKeyViolation) insert or update on table "match" violates foreign key constraint "match_away_team_id_fkey"
DETAIL:  Key (away_team_id)=(3331) is not present in table "country".

[SQL: INSERT INTO match (date, round, confirmed, home_score, away_score, home_team_id, away_team_id) VALUES (%(date)s, %(round)s, %(confirmed)s, %(home_score)s, %(away_score)s, %(home_team_id)s, %(away_team_id)s) RETURNING match.id]
[parameters: {'date': '1980-1-1', 'round': 4, 'confirmed': False, 'home_score': None, 'away_score': None, 'home_team_id': 178, 'away_team_id': 3331}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-13 11:51:05,518 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:51:05] "[32mGET /match/create-new/178/3331/4 HTTP/1.1[0m" 302 -
2022-12-13 11:51:05,533 :: INFO :: 127.0.0.1 - - [13/Dec/2022 11:51:05] "GET /match/all HTTP/1.1" 200 -
2022-12-13 14:04:09,822 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:04:09,822 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:04:45,605 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:04:45] "GET / HTTP/1.1" 200 -
2022-12-13 14:04:55,648 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:04:55] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-13 14:04:55,661 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:04:55] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:05:16,967 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:16] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-13 14:05:16,972 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:16] "GET / HTTP/1.1" 200 -
2022-12-13 14:05:19,131 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:19] "[32mGET /profile_auth_test HTTP/1.1[0m" 302 -
2022-12-13 14:05:19,137 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:19] "GET /auth/login?next=%2Fprofile_auth_test HTTP/1.1" 200 -
2022-12-13 14:05:24,784 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:05:24,784 :: ERROR :: Wrong credentials input
2022-12-13 14:05:24,785 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:24] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:05:24,791 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:24] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:05:30,934 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:05:30,934 :: ERROR :: Wrong credentials input
2022-12-13 14:05:30,935 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:30] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:05:30,941 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:30] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:05:45,233 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:05:45,234 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:45] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:05:45,244 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:45] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:05:56,011 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:05:56] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:06:33,275 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:06:33] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-13 14:06:33,285 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:06:33] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:16:45,680 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:16:45,680 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:16:55,427 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:16:55,428 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:16:55] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:16:55,445 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:16:55] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:17:03,281 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:17:03] "[33mGET /moderator-test HTTP/1.1[0m" 404 -
2022-12-13 14:17:10,752 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:17:10] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:18:19,430 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:18:19,430 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:18:22,144 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:22] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:18:30,986 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:30] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:18:39,460 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:39] "GET /lineup/full HTTP/1.1" 200 -
2022-12-13 14:18:46,233 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:46] "[32mGET /auth/logout HTTP/1.1[0m" 302 -
2022-12-13 14:18:46,250 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:46] "GET / HTTP/1.1" 200 -
2022-12-13 14:18:48,079 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:48] "[32mGET /profile_auth_test HTTP/1.1[0m" 302 -
2022-12-13 14:18:48,089 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:48] "GET /auth/login?next=%2Fprofile_auth_test HTTP/1.1" 200 -
2022-12-13 14:18:49,313 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:49] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:18:56,150 :: INFO :: [(bla), (bla@mail.com), (user)]
2022-12-13 14:18:56,151 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:56] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:18:56,160 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:18:56] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:19:02,961 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:02] "[32mGET /auth/moderator-test HTTP/1.1[0m" 302 -
2022-12-13 14:19:02,969 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:02] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:19:06,384 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:06] "[32mGET /auth/admin-test HTTP/1.1[0m" 302 -
2022-12-13 14:19:06,392 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:19:06] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:22:44,321 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:22:44,321 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:23:08,231 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:08] "GET /auth/login HTTP/1.1" 200 -
2022-12-13 14:23:17,825 :: INFO :: [(admin), (admin@mail.com), (admin)]
2022-12-13 14:23:17,826 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:17] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2022-12-13 14:23:17,836 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:17] "GET /profile_auth_test HTTP/1.1" 200 -
2022-12-13 14:23:41,247 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:41] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:23:44,519 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:23:44] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:31:00,440 :: INFO :: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.0.251:5000
2022-12-13 14:31:00,440 :: INFO :: [33mPress CTRL+C to quit[0m
2022-12-13 14:31:05,968 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:31:05] "GET /auth/admin-test HTTP/1.1" 200 -
2022-12-13 14:31:12,517 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:31:12] "GET /auth/moderator-test HTTP/1.1" 200 -
2022-12-13 14:45:48,690 :: INFO :: 127.0.0.1 - - [13/Dec/2022 14:45:48] "GET /auth/moderator-test HTTP/1.1" 200 -
